### ISSUE TITLE
API 통신: Main화면 불러오기

### ISSUE THREAD

**Issue by jinsu4755** [team-nutee/NUTEE-Android#16]

**Comment by jinsu4755** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String kr.nutee.nutee_android.data.main.home.ImageXXX.getSrc()' on a null object reference
        at kr.nutee.nutee_android.ui.main.fragment.home.HomeViewHolder.bind(HomeViewHolder.kt:20)
        at kr.nutee.nutee_android.ui.main.fragment.home.HomeAdapter.onBindViewHolder(HomeAdapter.kt:26)
        at kr.nutee.nutee_android.ui.main.fragment.home.HomeAdapter.onBindViewHolder(HomeAdapter.kt:12)

위 에러 고치기

**Comment by jinsu4755** [comment]
data class받을때 call<List<Response>> or 형식 바꿔보기
